name: Benchmark SQL Regressions

on:
  pull_request:
    branches: [ main ]

jobs:
  set-version-actor:
    name: Set Version and Actor
    runs-on: ubuntu-22.04
    outputs:
      to_version: ${{ steps.set-vars.outputs.to_version }}
      from_version: ${{ steps.set-from.outputs.from_version }}
      actor: ${{ steps.set-vars.outputs.actor }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
      - name: Set From Version
        id: set-from
        run: |
          sha=$(git rev-parse --short HEAD)
          echo "from_version=$sha" >> $GITHUB_OUTPUT
      - name: Set variables
        id: set-vars
        run: |
          short_to=${TO_VERSION:0:8}
          echo "to_version=$short_to" >> $GITHUB_OUTPUT
          echo "actor=$ACTOR" >> $GITHUB_OUTPUT
        env:
          TO_VERSION: ${{ github.sha }}
          ACTOR: ${{ github.event.client_payload.actor || github.actor }}
  test:
    runs-on: ubuntu-22.04
    needs: set-version-actor
    name: Test values
    steps:
      - name: Echo vals
        run: |
          echo "FROM_VERSION: $FROM_VERSION"
          echo "TO_VERSION: $TO_VERSION"
        env:
          FROM_VERSION: ${{ needs.set-version-actor.outputs.from_version }}
          TO_VERSION: ${{ needs.set-version-actor.outputs.to_version }}

  regressions:
    runs-on: ubuntu-22.04
    needs: set-version-actor
    name: Trigger SQL Regressions K8s Workflow
    steps:
      - uses: peter-evans/repository-dispatch@v2.0.0
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: sql-correctness
          client-payload: '{"from_version": "${{ needs.set-version-actor.outputs.from_version }}", "to_version": "${{ needs.set-version-actor.outputs.to_version }}", "mode": "release", "actor": "${{ needs.set-version-actor.outputs.actor }}", "actor_email": "${{ needs.set-version-actor.outputs.actor_email }}", "template_script": "./.github/scripts/sql-correctness/get-dolt-regressions-job-json.sh"}'
