on:
#  repository_dispatch:
#    types: [ dolt-prerelease ]
  workflow_dispatch:
    inputs:
      version:
        description: 'SemVer format release tag, i.e. 0.24.5'
        required: true
        default: ''

jobs:
  set-version-actor:
    name: Set Version and Actor
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.set-vars.outputs.version }}
      actor: ${{ steps.set-vars.outputs.actor }}
      actor_email: ${{ steps.set-vars.outputs.actor_email }}
    steps:
      - name: Set variables
        id: set-vars
        run: |
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "actor=$ACTOR" >> $GITHUB_OUTPUT
          echo "actor_email=$ACTOR_EMAIL" >> $GITHUB_OUTPUT
        env:
          VERSION: ${{ github.event.inputs.version || github.event.client_payload.version }}
          ACTOR: ${{ github.event.client_payload.actor || github.actor }}
          ACTOR_EMAIL: ${{ github.event.inputs.email }}

  profile-benchmark-dolt:
    runs-on: ubuntu-22.04
    needs: set-version-actor
    name: Trigger Benchmark Profile K8s Workflows
    steps:
      - uses: peter-evans/repository-dispatch@v2.0.0
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: profile-dolt
          client-payload: '{"from_version": "${{ needs.set-version-actor.outputs.version }}", "mode": "release", "actor": "${{ needs.set-version-actor.outputs.actor }}", "actor_email": "${{ needs.set-version-actor.outputs.actor_email }}", "template_script": "./.github/scripts/performance-benchmarking/get-dolt-profile-job-json.sh"}'
